---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: manifestor
  namespace: reckerbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manifestor
  namespace: reckerbot
rules:
- apiGroups: [""]
  resources:
  - deployments
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manifestor
subjects:
- kind: ServiceAccount
  name: manifestor
roleRef:
  kind: Role
  name: manifestor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manifestor
  namespace: reckerbot
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: manifestor
          containers:
          - name: manifestor
            image: arecker/manifestor:latest
            env:
            - name: MANIFEST_URL
              value: https://raw.githubusercontent.com/arecker/reckerbot/master/deploy/deployment.yml
