name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: make install-test-deps
      - run: make lint
      - run: make test
